
//DASHBOARD
export const RECEIVE_DASHBOARD = 'RECEIVE_DASHBOARD';
export const REQUEST_DASHBOARD = 'REQUEST_DASHBOARD';
//TESTS
export const RECEIVE_TEST = 'RECEIVE_TEST';
export const REQUEST_TEST = 'REQUEST_TEST';
//START_TEST
export const POST_TEST = 'POST_TEST';
export const SELECT_TEST = 'SELECT_TEST';
export const POST_REQUEST_LESSON_STEP = 'POST_REQUEST_LESSON_STEP';
