export const SEARCH_TEXT = 'SEARCH_TEXT';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';


export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const LOGIN_USER_LOGOUT = 'LOGIN_USER_LOGOUT';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';

export const SEND_MAIL =  'SEND_MAIL'
export const RECEIVE_SEND_MAIL =  'RECEIVE_SEND_MAIL'

export const RESET_PASSWORD =  'RESET_PASSWORD'
export const RECEIVE_RESET_PASSWORD =  'RECEIVE_RESET_PASSWORD'


//TITLE
export const TITLE = 'TITLE';
export const REQUEST_TITLE = 'REQUEST_TITLE';
export const RECEIVE_TITLE = 'RECEIVE_TITLE';

//QUIZ
export const RECEIVE_TEST = 'RECEIVE_TEST';
export const REQUEST_SCORE = 'REQUEST_SCORE';
export const RECEIVE_SCORE = 'RECEIVE_SCORE';
export const RESET_SCORE = 'RESET_SCORE';

export const CURRENT_ANSWER = 'CURRENT_ANSWER';
export const NEXT_SLIDE = 'NEXT_SLIDE';

//SHOP
export const USER_BALANCE = 'USER_BALANCE';
export const PRODUCTS_LIST = 'PRODUCTS_LIST';
export const BUY_PRODUCT = 'BUY_PRODUCT';


export const RECEIVE_BALANCE = 'RECEIVE_BALANCE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';

export const RECEIVE_SEND_PROD_SHOP = "RECEIVE_SEND_PROD_SHOP";
export const REQUEST_SEND_PROD_SHOP = "REQUEST_SEND_PROD_SHOP";

//SAMSUNG ++
export const GET_LESSONS_PLUS_PLUS = 'GET_LESSONS_PLUS_PLUS';
export const RECEIVE_LESSONS_PLUS_PLUS = "RECEIVE_LESSONS_PLUS_PLUS";
export const REQUEST_LESSONS_PLUS_PLUS = "REQUEST_LESSONS_PLUS_PLUS";
export const RECEIVE_TEST_PLUS_PLUS = "RECEIVE_TEST_PLUS_PLUS";
export const REQUEST_ACTIVE_TEST_PLUS_PLUS = "REQUEST_ACTIVE_TEST_PLUS_PLUS";
export const JOIN_LESSON_PLUS_PLUS = "JOIN_LESSON_PLUS_PLUS";
export const RECEIVE_AUTH_STATUS_PLUS_PLUS = "RECEIVE_AUTH_STATUS_PLUS_PLUS";
export const RECEIVE_LESSON_STATUS_PLUS_PLUS = "RECEIVE_LESSON_STATUS_PLUS_PLUS";
export const REQUEST_LESSON_STATUS_PLUS_PLUS = "REQUEST_LESSON_STATUS_PLUS_PLUS";
export const SAVE_SELECTED_LESSON_PLUS_PLUS = "SAVE_SELECTED_LESSON_PLUS_PLUS";
export const REQUEST_JOIN_LESSON_PLUS_PLUS = "REQUEST_JOIN_LESSON_PLUS_PLUS";
export const SUBMIT_ANSWER_PLUS_PLUS = "SUBMIT_ANSWER_PLUS_PLUS";
export const START_TEST_PLUS_PLUS = "START_TEST_PLUS_PLUS";
export const START_TEST = "START_TEST";

//REGISTRATION SALES
export const IS_APPROVED_REGIST = "IS_APPROVED_REGIST";
export const RECEIVE_IS_APPROVED_REGISTRATION = "RECEIVE_IS_APPROVED_REGISTRATION";
export const REQUEST_IS_APPROVED_REGISTRATION = "REQUEST_IS_APPROVED_REGISTRATION";
export const RECEIVE_REGIST_SALE = "RECEIVE_REGIST_SALE";
export const REQUEST_REGIST_SALE = "REQUEST_REGIST_SALE";

//ACCOUNT
export const CORRECT_ACCOUNT = 'CORRECT_ACCOUNT';
export const GET_NEWS = 'GET_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';
export const REQUEST_NEWS = 'REQUEST_NEWS';
export const BOUGHT_PRODUCTS_LIST = 'BOUGHT_PRODUCTS_LIST';
export const RECEIVE_BOUGHT_PRODUCTS = 'RECEIVE_BOUGHT_PRODUCTS';


//SCORE
export const GET_SCORE_TOTAL = 'GET_SCORE_TOTAL';
export const RECEIVE_SCORE_TOTAL = 'RECEIVE_SCORE_TOTAL';
export const REQUEST_SCORE_TOTAL = 'REQUEST_SCORE_TOTAL';

//NOTES
export const GET_NOTES = 'GET_NOTES';
export const REQUEST_NOTES = 'REQUEST_NOTES';
export const RECEIVE_NOTES = 'RECEIVE_NOTES';

export const GET_LESSON_NOTES = 'GET_LESSON_NOTES';
export const REQUEST_LESSONS_NOTES = 'REQUEST_LESSONS_NOTES';
export const RECEIVE_LESSONS_NOTES = 'RECEIVE_LESSONS_NOTES';

//LOGOUT
export const LOGOUT = 'LOGOUT';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

//RECEIVE_SAMSUNG_LESSONS
export const RECEIVE_SAMSUNG_LESSONS = 'RECEIVE_SAMSUNG_LESSONS';

//DIC
export const REQUEST_DICTIONARY = 'REQUEST_DICTIONARY';
export const RECEIVE_DICTIONARY = 'RECEIVE_DICTIONARY';

//lessons constants
export const REQUEST_ACTIVE_TEST = 'REQUEST_ACTIVE_TEST';
export const REQUEST_TEST_STATUS = 'REQUEST_TEST_STATUS';
export const REQUEST_LESSONS = 'REQUEST_LESSONS';
export const RECEIVE_LESSONS = 'RECEIVE_LESSONS';
export const REQUEST_JOIN_LESSON = 'REQUEST_JOIN_LESSON';
export const RECEIVE_LESSON_STATUS = 'RECEIVE_LESSON_STATUS';
export const REQUEST_LESSON_STATUS = 'REQUEST_LESSON_STATUS';

export const SAVE_SELECTED_LESSON = 'SAVE_SELECTED_LESSON';

//profile constants
export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';

export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';

export const SET_STEP = 'SET_STEP';
export const RECEIVE_AUTH_STATUS = 'RECEIVE_AUTH_STATUS';